package it.cai.cividale.server.domain;
// Generated 15-ott-2019 11.50.50 by Hibernate Tools 5.2.12.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Cassa generated by hbm2java
 */
@Entity
@Table(name = "cassa", catalog = "scuolacai")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Cassa implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    private Long id;

    @Column(name = "nota")
    private String nota;

    @OneToMany(cascade = CascadeType.ALL)
    private List<RipartizioneCassa> ripartizioniCassa = new ArrayList<>();

}
