package it.cai.cividale.server.domain;
// Generated 15-ott-2019 11.50.50 by Hibernate Tools 5.2.12.Final

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Dizmateriale generated by hbm2java
 */
@Entity
@Table(name = "diz_comune", catalog = "scuolacai")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class DizComune implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    private Long id;

    @Column(name = "comune", nullable = false)
    private String comune;

    @Column(name = "cap")
    private String cap;

    @Column(name = "provincia")
    private String provincia;

    @Column(name = "sigla")
    private String sigla;

    @Column(name = "regione")
    private String regione;

}
