<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="http://it.caicividale.scuola.emf.model" nsPrefix="it.caicividale.scuola.emf.model">
  <eClassifiers xsi:type="ecore:EClass" name="Persona">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nome" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cognome" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sesso" eType="#//ESesso"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numeroCellulare" eType="#//NumeroCellulare"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eMail" eType="#//EMail"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="residenzaVia" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="residenzaCitta" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="residenzaProvincia" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="residenzaCap" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nascitaData" lowerBound="1"
        eType="#//ELocalDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nascitaCitta" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nascitaProvincia" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sezioneCaiAppartenenza"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isStaffScuola" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ESesso">
    <eLiterals name="MASCHIO" literal="M"/>
    <eLiterals name="FEMMINA" value="1" literal="F"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="NumeroCellulare" instanceClassName="it.caicividale.scuola.emf.model.valueobject.NumeroCellulare"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EMail" instanceClassName="it.caicividale.scuola.emf.model.valueobject.EMail"/>
  <eClassifiers xsi:type="ecore:EClass" name="Allievo" eSuperTypes="#//Persona">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDiploma" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Corso">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anno" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="quotaIscrizione" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloatObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="quotaCaparra" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloatObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isModulo" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="False"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="direttore" lowerBound="1"
        eType="#//Istruttore" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="viceDirettore" eType="#//Istruttore"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="segretario" lowerBound="1"
        eType="#//Persona" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="testo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bilancio" eType="#//Bilancio"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cassa" eType="#//Cassa"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataInizio" lowerBound="1"
        eType="#//ELocalDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataFine" lowerBound="1"
        eType="#//ELocalDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="staffIstruttori" upperBound="-1"
        eType="#//Istruttore" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nome" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sigla" lowerBound="1" eType="#//ESiglaCorso"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="equipaggiamento" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numeroAllievi" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numeroAllieviIscrizioneOk"
        ordered="false" unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numeroAllieviIscrizioneKo"
        ordered="false" unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numeroAllieviNuoviIscritti"
        ordered="false" unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numeroAllieviMaschi" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numeroAllieviFemmine" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numeroAllieviConNoleggio"
        ordered="false" unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="listRiepilogonoleggio"
        ordered="false" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="moduli" upperBound="-1"
        eType="#//Corso" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lezioniPratiche" upperBound="-1"
        eType="#//LezionePratica" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lezioniTeoriche" upperBound="-1"
        eType="#//LezioneTeorica" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="iscrizioni" upperBound="-1"
        eType="#//Iscrizione" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Iscrizione">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isModuloIscrizione" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="False"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isConsensoInformato" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="False"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isNuovoAllievo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="False"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataScadenzaCertificatoMedico"
        eType="#//ELocalDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isBollinoAnnoCorso" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="False"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="caparra" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloatObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="saldo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloatObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totaleVersato" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloatObject"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="note" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isNoleggio" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        changeable="false" volatile="true" transient="true" defaultValueLiteral="False"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="materialeNoleggiato" upperBound="-1"
        eType="#//MaterialeNoleggiato" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isIscrizioneOk" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="False"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="quotaNoleggio" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloatObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isCertificatoMedico" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="False"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isCertificatoMedicoOk"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="False"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isQuotaVersataOk" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        changeable="false" volatile="true" transient="true" defaultValueLiteral="False"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="quotaNoleggioDaVersare"
        ordered="false" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloatObject"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totaleDaVersare" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloatObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="differenzaTotaleVersatoTotaleDaVersare"
        ordered="false" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloatObject"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="messaggiErrore" ordered="false"
        unique="false" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allievo" lowerBound="1"
        eType="#//Allievo" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Lezione">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="titolo" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataSvolgimento" eType="#//ELocalDateTime"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="luogoSvolgimento" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="durata" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloatObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="presenzaLezione" lowerBound="1"
        eType="#//PresenzaLezione" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="argomentiTrattati" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LezioneTeorica" eSuperTypes="#//Lezione">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Docente" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LezionePratica" eSuperTypes="#//Lezione">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="luogoRitrovo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="squadre" lowerBound="1"
        upperBound="-1" eType="#//Squadra" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Istruttore" eSuperTypes="#//Persona">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="titolo" lowerBound="1"
        eType="#//ETitoloIstruttore"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAttivo" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ETitoloIstruttore">
    <eLiterals name="ISTRUTTORE_SEZIONALE" literal="IS"/>
    <eLiterals name="ISTRUTTORE_ALPINISMO" value="1" literal="IA"/>
    <eLiterals name="ISTRUTTORE_SCIALPINISMO" value="2" literal="ISA"/>
    <eLiterals name="ISTRUTTORE_SCI_FONDO_ESCURSIONISMO" value="3" literal="ISFE"/>
    <eLiterals name="ISTRUTTORE_NAZIONALE_ALPINISMO" value="4" literal="INA"/>
    <eLiterals name="ISTRUTTORE_NAZIONALE_SCIALPINISMO" value="5" literal="INSA"/>
    <eLiterals name="ASPIRANTE_ISTRUTTORE" value="6" literal="ASP"/>
    <eLiterals name="ISTRUTTORE_ARRAMPICATA_LIBERA" value="7" literal="IAL"/>
    <eLiterals name="ISTRUTTORE_NAZIONALE_ARRAMPICATA_LIBERA" value="8" literal="INAL"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Squadra">
    <eStructuralFeatures xsi:type="ecore:EReference" name="capoSquadra" lowerBound="1"
        eType="#//Istruttore" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allieviInSquadra" lowerBound="1"
        upperBound="-1" eType="#//Allievo" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nome" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="staffSquadra" upperBound="-1"
        eType="#//Istruttore" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TipoEsitoValutazione">
    <eLiterals name="OTTIMO" literal="O"/>
    <eLiterals name="BUONO" value="1" literal="B"/>
    <eLiterals name="SUFFICIENTE" value="2" literal="S"/>
    <eLiterals name="INSUFFICIENTE" value="3" literal="I"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bilancio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vociDiSpesa" upperBound="-1"
        eType="#//VoceDiSpesa" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nota" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totaleEntrate" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totaleUscite" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totaleIscrizioni" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totaleEntrateConIscrizioni"
        ordered="false" unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="avanzoCorso" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cassa">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totale" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ripartizioniCassa" upperBound="-1"
        eType="#//RipartizioneCassa" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nota" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="differenzaTotaleCasseEAvanzo"
        ordered="false" unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RipartizioneCassa">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sede" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="quota" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PresenzaLezione">
    <eStructuralFeatures xsi:type="ecore:EReference" name="allieviPresenti" upperBound="-1"
        eType="#//Allievo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="istruttoriPresenti" upperBound="-1"
        eType="#//Istruttore"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DizMateriale">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nome" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nota" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="quotaNoleggio" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MaterialeNoleggiato">
    <eStructuralFeatures xsi:type="ecore:EReference" name="materiale" lowerBound="1"
        eType="#//DizMateriale" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="quantita" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataNoleggio" lowerBound="1"
        eType="#//ELocalDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ESiglaCorso">
    <eLiterals name="A1"/>
    <eLiterals name="A1N" value="1"/>
    <eLiterals name="A1R" value="2"/>
    <eLiterals name="A1G" value="3"/>
    <eLiterals name="SA1" value="4"/>
    <eLiterals name="SA2" value="5"/>
    <eLiterals name="AR1" value="6"/>
    <eLiterals name="AR2" value="7"/>
    <eLiterals name="AG1" value="8"/>
    <eLiterals name="AG2" value="9"/>
    <eLiterals name="ACG1" value="10"/>
    <eLiterals name="AL1" value="11"/>
    <eLiterals name="AL2" value="12"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VoceDiSpesa">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="titolo" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valore" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipo" lowerBound="1" eType="#//ETipoVoceDiSpesa"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nota" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="data" lowerBound="1" eType="#//ELocalDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ETipoVoceDiSpesa">
    <eLiterals name="ENTRATA"/>
    <eLiterals name="USCITA" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElencoCorsi">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elencoCorsi" upperBound="-1"
        eType="#//Corso" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElencoIscrizioni">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elencoIscrizioni" upperBound="-1"
        eType="#//Iscrizione" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ELocalDate" instanceClassName="java.time.LocalDate"/>
  <eClassifiers xsi:type="ecore:EDataType" name="ELocalDateTime" instanceClassName="java.time.LocalDateTime"/>
  <eClassifiers xsi:type="ecore:EClass" name="ElencoMateriali">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elencoMateriali" upperBound="-1"
        eType="#//DizMateriale" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElencoIstruttori">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elencoIstruttori" upperBound="-1"
        eType="#//Istruttore" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
