package it.cai.cividale.server.domain;
// Generated 15-ott-2019 11.50.50 by Hibernate Tools 5.2.12.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.OneToMany;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

/**
 * Lezionepratica generated by hbm2java
 */
@Entity
@Table(name = "lezione_pratica", catalog = "scuolacai")
@PrimaryKeyJoinColumn(name = "id")
@Data
@EqualsAndHashCode(callSuper = false)
@AllArgsConstructor
@NoArgsConstructor
public class LezionePratica extends Lezione implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    @Column(name = "luogoritrovo")
    private String luogoritrovo;

    @OneToMany(cascade = CascadeType.ALL)
    private List<Squadra> squadre = new ArrayList<>();

}
